name: Release

on:
  push:
    tags:
      - "*"

jobs:
  binaries:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          token: ${{ secrets.API_GITHUB_TOKEN }}

      - name: Setup Go environment
        uses: actions/setup-go@v3.0.0
        with:
          go-version: "1.18.1"

      - name: Binaries Release
        uses: goreleaser/goreleaser-action@v2.9.1
        with:
          version: ~> 0.175
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
